version: '2'

services:
  seed:
    image: ikuo/cat-cluster:latest
    ports: ["8081:8080", "2551:2551"]
    restart: always
    environment:
      CONFIG: /seed.conf
      SEED_ADDR: akka.tcp://cluster@seed:2551
      AKKA_HOSTNAME: seed

  cat: &cat
    image: ikuo/cat-cluster:latest
    restart: always
    environment: &environment
      CONFIG: /cat.conf
      SEED_ADDR: akka.tcp://cluster@seed:2551
      SENSOR_INTERVAL: 100.millis
      PROFILER_STDOUT: 'true'
      AKKA_HOSTNAME:
