version: '2'

services:
  redis:
    image: redis:2.8.23
    expose:
      - "6379"

  seed: &seed
    image: ${USER}/cat-cluster:latest
    ports: ["8081:8080", "2551:2551"]
    restart: always
    environment: &environment
      CONFIG: /seed.conf
      SEED_ADDR: akka.tcp://cluster@seed:2551
      AKKA_HOSTNAME: seed
      REDIS_HOST: redis

  cat:
    image: ${USER}/cat-cluster:latest
    restart: always
    environment:
      <<: *environment
      CONFIG: /cat-${ENV}.conf
      MAX_HEAP_SIZE: 300m
      AKKA_HOSTNAME:

  sensor:
    image: ${USER}/cat-cluster:latest
    restart: always
    environment:
      <<: *environment
      CONFIG: /sensor-${ENV}.conf
      MAX_HEAP_SIZE: 30m
      AKKA_HOSTNAME:
