version: '2'

networks:
  faulty-cat:

services:
  redis:
    image: redis:2.8.23
    expose:
      - "6379"
    networks:
      - faulty-cat

  seed: &seed
    image: ${USER}/cat-cluster:latest
    ports: ["8081:8080", "2551:2551"]
    restart: always
    environment: &environment
      CONFIG: /seed.conf
      SEED_ADDR: akka.tcp://cluster@seed:2551
      AKKA_HOSTNAME: seed
      REDIS_HOST: redis
    networks:
      - faulty-cat

  cat:
    image: ${USER}/cat-cluster:latest
    restart: always
    environment:
      <<: *environment
      CONFIG: /cat-${ENV}.conf
      MAX_HEAP_SIZE: 2000m
      AKKA_HOSTNAME:
    networks:
      - faulty-cat

  sensor:
    image: ${USER}/cat-cluster:latest
    restart: always
    environment:
      <<: *environment
      CONFIG: /sensor-${ENV}.conf
      MAX_HEAP_SIZE: 30m
      AKKA_HOSTNAME:
    networks:
      - faulty-cat

  gremlins:
    image: qualimente/gremlins
    volumes:
      - ./gremlins:/app/gremlins/profiles
    command: gremlins -m gremlins.profiles.sensor -p sensor.profile
    network_mode: "service:sensor"
    cap_add:
      - NET_ADMIN
