version: '2'

services:
  redis:
    image: redis:2.8.23
    expose:
      - "6379"

  seed: &seed
    image: ikuo/cat-cluster:latest
    ports: ["8081:8080", "2551:2551"]
    restart: always
    environment: &environment
      CONFIG: /seed.conf
      SEED_ADDR: akka.tcp://cluster@seed:2551
      AKKA_HOSTNAME: seed
      CATS_MAX: 120e+6
      REDIS_HOST: redis
      CAT_REMEMBER_ENTITIES: 'false'
      PROFILER_STDOUT: 'true'

  cat:
    image: ikuo/cat-cluster:latest
    restart: always
    environment:
      <<: *environment
      CONFIG: /cat.conf
      LOGLEVEL: INFO
      MAX_HEAP_SIZE: 300m
      AKKA_HOSTNAME:

  sensor:
    image: ikuo/cat-cluster:latest
    restart: always
    environment:
      <<: *environment
      CONFIG: /sensor.conf
      SENSOR_INTERVAL: 300.millis
      SENSOR_BATCH_SIZE: 100
      MAX_HEAP_SIZE: 30m
      AKKA_HOSTNAME:
