seed:
  image: ikuo/cat-cluster:latest
  ports: ["8081:8080", "2551:2551"]
  environment:
    CONFIG: /seed.conf
    SEED_ADDR: akka.tcp://cluster@seed:2551
    AKKA_HOSTNAME: seed

cat1:
  image: ikuo/cat-cluster:latest
  ports: ["8082:8080", "2552:2552"]
  environment:
    CONFIG: /cat.conf
    SEED_ADDR: akka.tcp://cluster@seed:2551
    AKKA_HOSTNAME: cat1
    AKKA_PORT: 2552
    SENSOR_INTERVAL: 100.millis
    PROFILER_STDOUT: 'true'
  links:
    - seed:seed
